import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service | HomeCalc',
  description: 'HomeCalc Terms of Service and User Agreement',
}

const EFFECTIVE_DATE = 'February 24, 2026'
const LAST_UPDATED   = 'February 24, 2026'

export default function TermsPage() {
  return (
    <div style={{
      minHeight: '100vh',
      background: '#0a0f1e',
      fontFamily: '"DM Sans","Helvetica Neue",Arial,sans-serif',
      color: '#c8d4d4',
    }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500;9..40,700;9..40,900&display=swap');
        * { box-sizing:border-box; margin:0; padding:0; }
        ::-webkit-scrollbar { width:1px }
        ::-webkit-scrollbar-thumb { background:rgba(100,200,200,.15) }
        ::selection { background:#1a2f3a; color:#e0f4f4 }
      `}</style>

      {/* Nav */}
      <nav style={{
        position:'sticky', top:0, zIndex:100,
        display:'flex', alignItems:'center', justifyContent:'space-between',
        padding:'0 40px', height:52,
        borderBottom:'1px dashed rgba(255,255,255,0.08)',
        background:'rgba(10,15,30,0.92)',
        backdropFilter:'blur(16px)',
      }}>
        <Link href="/" style={{ fontSize:15, fontWeight:900, color:'#fff', textDecoration:'none', letterSpacing:'-0.03em' }}>
          🏠 HomeCalc
        </Link>
        <Link href="/" style={{
          padding:'7px 16px', borderRadius:6, fontSize:12, fontWeight:600,
          color:'rgba(208,216,216,0.6)', textDecoration:'none',
          border:'1px solid rgba(255,255,255,0.1)',
        }}>
          ← Back to Home
        </Link>
      </nav>

      {/* Content */}
      <main style={{ maxWidth:780, margin:'0 auto', padding:'60px 40px 100px' }}>

        {/* Header */}
        <div style={{ marginBottom:48 }}>
          <div style={{
            display:'inline-block', padding:'3px 10px', borderRadius:4, marginBottom:20,
            background:'rgba(100,210,200,0.08)', border:'1px solid rgba(100,210,200,0.18)',
            fontSize:9, fontWeight:800, letterSpacing:'0.12em', textTransform:'uppercase',
            color:'rgba(100,210,200,0.65)',
          }}>
            Legal Agreement
          </div>
          <h1 style={{ fontSize:38, fontWeight:900, color:'#fff', letterSpacing:'-0.04em', lineHeight:1.1, marginBottom:14 }}>
            Terms of Service<br />
            <span style={{ color:'rgba(208,216,216,0.3)', fontSize:28 }}>& User Agreement</span>
          </h1>
          <p style={{ fontSize:12, color:'rgba(208,216,216,0.35)', lineHeight:1.6 }}>
            Effective Date: {EFFECTIVE_DATE} · Last Updated: {LAST_UPDATED}
          </p>
          <div style={{
            marginTop:24, padding:'14px 18px', borderRadius:8,
            background:'rgba(220,38,38,0.07)', border:'1px solid rgba(220,38,38,0.18)',
            fontSize:11, color:'rgba(248,113,113,0.75)', lineHeight:1.7,
          }}>
            <strong>PLEASE READ THIS AGREEMENT CAREFULLY.</strong> By accessing or using the HomeCalc platform
            (&quot;Platform&quot;), you acknowledge that you have read, understood, and agree to be legally bound
            by these Terms of Service (&quot;Agreement&quot;). If you do not agree to all terms herein, you must
            immediately cease use of the Platform.
          </div>
        </div>

        {/* Sections */}
        {[
          {
            num: '1.',
            title: 'Definitions',
            body: `For purposes of this Agreement, the following terms shall have the meanings ascribed to them herein:

"Platform" means the HomeCalc web application, including all pages, calculators, tools, reports, dashboards, and associated services accessible at home-calculator-self.vercel.app and any successor domains.

"Operator" means the individual or entity that owns, operates, and maintains the Platform.

"User" or "you" means any individual who accesses, browses, registers for, or otherwise uses the Platform.

"Outputs" means any and all computational results, estimates, projections, schedules, analyses, reports, or other data generated by the Platform in response to User inputs, including without limitation mortgage payment estimates, tax calculations, debt-to-income ratios, amortization schedules, investment projections, and affordability analyses.

"User Content" means any data, information, or content you submit to the Platform, including financial inputs, account credentials, and saved scenarios.`,
          },
          {
            num: '2.',
            title: 'Nature of Service — No Professional Advisory Relationship',
            body: `2.1 Informational and Educational Purpose Only. The Platform and all Outputs are provided solely for general informational and educational purposes. Nothing on the Platform constitutes, and nothing shall be construed as constituting, financial advice, investment advice, mortgage advice, tax advice, accounting advice, legal advice, or any other form of professional advisory service within the meaning of any applicable federal or state statute, regulation, or rule, including without limitation the Investment Advisers Act of 1940, as amended, or any analogous state statute.

2.2 No Professional Relationship Established. Your access to and use of the Platform does not create, and is not intended to create, any fiduciary relationship, attorney-client relationship, broker-dealer relationship, investment adviser-client relationship, accountant-client relationship, or any other professional advisory relationship between you and the Operator.

2.3 No Personalized Advice. The Outputs generated by the Platform are based solely upon the data inputs provided by you and do not account for your individual financial circumstances, creditworthiness, credit history, employment history, assets, liabilities, risk tolerance, investment objectives, tax situation, estate planning needs, insurance requirements, liquidity needs, or any other personal factors that a duly licensed and qualified professional would evaluate in rendering personalized advice.

2.4 Mandatory Professional Consultation. PRIOR TO MAKING ANY FINANCIAL DECISION, ENTERING INTO ANY MORTGAGE COMMITMENT, MAKING ANY INVESTMENT, OR TAKING ANY ACTION BASED IN WHOLE OR IN PART ON ANY OUTPUT FROM THE PLATFORM, YOU SHOULD INDEPENDENTLY CONSULT WITH: (a) a licensed mortgage loan originator or mortgage broker; (b) a Certified Public Accountant (CPA) or licensed tax professional; (c) a Registered Investment Adviser (RIA) registered with the U.S. Securities and Exchange Commission or applicable state authority; (d) a licensed real estate attorney; and/or (e) any other appropriately credentialed professional whose expertise is relevant to your specific situation.`,
          },
          {
            num: '3.',
            title: 'Accuracy of Data — Limitations and Disclaimer',
            body: `3.1 Data Currency. All federal income tax bracket thresholds, standard deduction amounts, FICA wage base limits, and related federal tax parameters reflected within the Platform are based upon data published by the Internal Revenue Service for the 2025 tax year. State income tax rates are based upon publicly available information current as of the date of last update identified above. Such data is subject to legislative, regulatory, and administrative change without notice and without obligation on the part of the Operator to update the Platform.

3.2 Property Tax Estimates. Property tax estimates generated by the Platform are based upon published statewide average effective property tax rates and do not reflect the specific millage rate, assessment ratio, exemption status (including homestead, senior, veteran, or other exemptions), or other factors applicable to any specific parcel of real property. Actual property tax liability may differ materially from any estimate provided by the Platform.

3.3 Mortgage and Insurance Estimates. Mortgage payment calculations assume a fixed loan structure unless otherwise specified and do not account for variable rate adjustments, prepayment penalties, escrow adjustments, flood insurance, earthquake insurance, HOA fees, or other costs that may be associated with property ownership or a specific loan product. Private mortgage insurance (PMI) estimates are approximations only and will not reflect the rate quoted by any specific insurer.

3.4 No Warranty. THE OPERATOR MAKES NO REPRESENTATION OR WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS, TIMELINESS, NON-INFRINGEMENT, OR THAT THE PLATFORM WILL OPERATE FREE OF ERROR OR INTERRUPTION. THE PLATFORM AND ALL OUTPUTS ARE PROVIDED "AS IS" AND "AS AVAILABLE."

3.5 User Responsibility to Verify. You are solely and entirely responsible for independently verifying the accuracy of all Outputs against current data from authoritative sources, including the Internal Revenue Service, applicable state department of revenue, your county assessor's office, your mortgage lender, and any other relevant authority, before relying upon any Output for any purpose.`,
          },
          {
            num: '4.',
            title: 'Investment Projections — Hypothetical Performance Disclosure',
            body: `4.1 Hypothetical Nature. Any investment return projections, portfolio growth estimates, or comparative analyses between mortgage paydown and market investment included within the Platform are purely hypothetical in nature, are based solely upon user-defined assumed rates of return, and are presented for illustrative purposes only.

4.2 No Guarantee of Performance. HYPOTHETICAL OR SIMULATED PERFORMANCE RESULTS HAVE CERTAIN INHERENT LIMITATIONS. UNLIKE AN ACTUAL PERFORMANCE RECORD, SIMULATED RESULTS DO NOT REPRESENT ACTUAL TRADING OR INVESTMENT RESULTS AND MAY NOT REFLECT THE IMPACT OF MATERIAL ECONOMIC AND MARKET FACTORS. PAST PERFORMANCE OF ANY INDEX, FUND, SECURITY, OR ASSET CLASS IS NOT INDICATIVE OF, AND DOES NOT GUARANTEE, FUTURE RESULTS. ALL INVESTMENTS INVOLVE RISK, INCLUDING THE POSSIBLE LOSS OF PRINCIPAL. YOU MAY RECEIVE BACK LESS THAN YOU INVEST.

4.3 Not a Securities Recommendation. Nothing in the Platform constitutes a recommendation, solicitation, or offer to buy or sell any security, fund, or other financial instrument.`,
          },
          {
            num: '5.',
            title: 'Limitation of Liability',
            body: `5.1 Exclusion of Damages. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE OPERATOR, ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, CONTRACTORS, AGENTS, LICENSORS, AND SERVICE PROVIDERS (COLLECTIVELY, "OPERATOR PARTIES") SHALL NOT BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES OF ANY KIND WHATSOEVER, INCLUDING WITHOUT LIMITATION LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF DATA, LOSS OF GOODWILL, OR LOSS ARISING FROM FINANCIAL DECISIONS MADE IN RELIANCE UPON OUTPUTS OF THE PLATFORM, EVEN IF ANY OPERATOR PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

5.2 Cap on Liability. TO THE EXTENT ANY LIABILITY IS FOUND NOTWITHSTANDING THE FOREGOING, THE AGGREGATE LIABILITY OF THE OPERATOR PARTIES TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATED TO THIS AGREEMENT OR THE PLATFORM SHALL NOT EXCEED THE GREATER OF (a) THE TOTAL FEES PAID BY YOU TO THE OPERATOR IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR (b) ONE HUNDRED DOLLARS (USD $100.00).

5.3 Essential Basis. THE PARTIES ACKNOWLEDGE THAT THE LIMITATIONS OF LIABILITY SET FORTH IN THIS SECTION 5 REFLECT A REASONABLE ALLOCATION OF RISK AND ARE AN ESSENTIAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN THE PARTIES. THE PLATFORM WOULD NOT BE PROVIDED WITHOUT SUCH LIMITATIONS.`,
          },
          {
            num: '6.',
            title: 'Indemnification',
            body: `You agree to indemnify, defend, and hold harmless the Operator Parties from and against any and all claims, actions, proceedings, demands, losses, damages, liabilities, costs, and expenses (including reasonable attorneys' fees and court costs) arising out of or relating to: (a) your access to or use of the Platform; (b) your User Content; (c) any financial decision made by you in reliance on any Output; (d) your breach of this Agreement; (e) your violation of any applicable law, rule, or regulation; or (f) your infringement of any third-party right, including any intellectual property right or privacy right.`,
          },
          {
            num: '7.',
            title: 'User Accounts and Data',
            body: `7.1 Account Registration. Certain features of the Platform require account registration. You agree to provide accurate, current, and complete information at registration and to maintain and update such information as necessary. You are solely responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.

7.2 Financial Data. All financial data you enter into the Platform is used solely to generate Outputs for your personal use. The Operator does not sell, rent, or share your individual financial inputs with third parties for marketing purposes. Data is stored in accordance with our Privacy Policy.

7.3 No Reliance by Third Parties. Outputs generated by the Platform are intended solely for your personal use. You shall not share, publish, or provide Platform Outputs to any third party (including any lender, real estate agent, employer, or government agency) as a substitute for documentation from a licensed professional.

7.4 Account Security. You agree to notify the Operator immediately upon becoming aware of any unauthorized access to or use of your account. The Operator shall not be liable for any loss or damage arising from your failure to maintain the security of your account credentials.`,
          },
          {
            num: '8.',
            title: 'Intellectual Property',
            body: `8.1 Platform Ownership. The Platform, including all software, algorithms, user interface designs, text, graphics, and other content created by the Operator (excluding User Content), is owned by the Operator and is protected by applicable copyright, trademark, patent, and other intellectual property laws. You are granted a limited, non-exclusive, non-transferable, revocable license to access and use the Platform solely for your personal, non-commercial use in accordance with this Agreement.

8.2 Restrictions. You shall not: (a) copy, modify, distribute, sell, or lease any part of the Platform; (b) reverse engineer, decompile, or attempt to extract the source code of the Platform; (c) use the Platform to develop a competing service; or (d) remove, obscure, or alter any proprietary notices on the Platform.`,
          },
          {
            num: '9.',
            title: 'Prohibited Uses',
            body: `You agree that you will not use the Platform: (a) for any unlawful purpose or in violation of any applicable federal, state, local, or international law or regulation; (b) to transmit any material that is fraudulent, false, misleading, or deceptive; (c) to impersonate any person or entity or falsely claim an affiliation with any person or entity; (d) to attempt to gain unauthorized access to any portion of the Platform or any other systems or networks connected to the Platform; (e) to introduce any virus, trojan horse, worm, logic bomb, or other malicious or technologically harmful material; (f) to engage in any automated data scraping, crawling, or collection of any content from the Platform without express written consent; or (g) to interfere with or disrupt the integrity or performance of the Platform or the data contained therein.`,
          },
          {
            num: '10.',
            title: 'Third-Party Services',
            body: `The Platform utilizes third-party services including, without limitation, Supabase (database and authentication), Vercel (hosting and deployment), and Google (authentication). Your use of such third-party services is subject to the respective terms of service and privacy policies of those providers. The Operator has no control over and assumes no responsibility for the content, privacy policies, or practices of any third-party services. References to any third-party service, product, or resource do not constitute an endorsement by the Operator.`,
          },
          {
            num: '11.',
            title: 'Disclaimer Regarding Tax Information',
            body: `THE PLATFORM DOES NOT PROVIDE TAX ADVICE. TAX LAWS AND REGULATIONS ARE SUBJECT TO CHANGE AND THE TAX CONSEQUENCES OF ANY FINANCIAL TRANSACTION DEPEND UPON A USER'S SPECIFIC FACTS AND CIRCUMSTANCES. THE TAX INFORMATION PROVIDED BY THE PLATFORM IS NOT INTENDED TO BE USED, AND CANNOT BE USED, BY ANY USER FOR THE PURPOSE OF AVOIDING FEDERAL OR STATE INCOME TAX PENALTIES. EACH USER SHOULD SEEK ADVICE FROM AN INDEPENDENT TAX ADVISOR BASED UPON THAT USER'S INDIVIDUAL CIRCUMSTANCES.`,
          },
          {
            num: '12.',
            title: 'Modifications to This Agreement',
            body: `The Operator reserves the right to amend, modify, or update this Agreement at any time at its sole discretion. Changes will be effective immediately upon posting of the revised Agreement to the Platform, with an updated "Last Updated" date. Your continued use of the Platform following the posting of any changes constitutes your acceptance of such changes. It is your responsibility to review this Agreement periodically. If you do not agree to any modification of this Agreement, you must cease using the Platform.`,
          },
          {
            num: '13.',
            title: 'Termination',
            body: `The Operator reserves the right, in its sole discretion, to suspend or terminate your access to the Platform at any time, with or without notice and with or without cause, including for your breach of this Agreement. Upon termination, all licenses granted to you under this Agreement shall immediately cease. Sections 2, 3, 4, 5, 6, 8, 13, 14, 15, and 16 of this Agreement shall survive termination.`,
          },
          {
            num: '14.',
            title: 'Governing Law and Dispute Resolution',
            body: `14.1 Governing Law. This Agreement and any dispute arising hereunder shall be governed by and construed in accordance with the laws of the State of Michigan, without regard to its conflict of law principles.

14.2 Dispute Resolution. Any dispute, claim, or controversy arising out of or relating to this Agreement or the Platform that cannot be resolved informally shall be submitted to binding arbitration administered by the American Arbitration Association under its Commercial Arbitration Rules, with proceedings conducted in the State of Michigan. The arbitrator's award shall be final and binding and may be entered as a judgment in any court of competent jurisdiction.

14.3 Class Action Waiver. YOU AND THE OPERATOR AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN AN INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, COLLECTIVE, CONSOLIDATED, OR REPRESENTATIVE PROCEEDING.

14.4 Exception. Notwithstanding the foregoing, either party may seek injunctive or other equitable relief in any court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation, or violation of a party's intellectual property rights.`,
          },
          {
            num: '15.',
            title: 'Severability and Waiver',
            body: `If any provision of this Agreement is held by a court or arbitrator of competent jurisdiction to be invalid, illegal, or unenforceable for any reason, such provision shall be modified to the minimum extent necessary to make it enforceable, or if modification is not possible, such provision shall be severed from this Agreement, and the remaining provisions shall continue in full force and effect. No waiver by the Operator of any term or condition set forth in this Agreement shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure by the Operator to assert a right or provision under this Agreement shall not constitute a waiver of such right or provision.`,
          },
          {
            num: '16.',
            title: 'Entire Agreement',
            body: `This Agreement constitutes the entire agreement between you and the Operator with respect to the Platform and supersedes all prior and contemporaneous understandings, agreements, representations, and warranties, both written and oral, with respect to the Platform. No oral or written information or advice given by the Operator or any other party shall create a warranty or otherwise expand the scope of this Agreement.`,
          },
          {
            num: '17.',
            title: 'Contact Information',
            body: `If you have any questions regarding this Agreement, you may contact the Platform operator through the user account system. Please note that communications through the Platform do not constitute legal service of process and do not create any professional advisory relationship.`,
          },
        ].map(sec => (
          <div key={sec.num} style={{
            marginBottom: 36,
            paddingBottom: 36,
            borderBottom: '1px solid rgba(255,255,255,0.05)',
          }}>
            <h2 style={{
              fontSize: 14, fontWeight: 800, color: 'rgba(208,216,216,0.75)',
              letterSpacing: '-0.01em', marginBottom: 12,
              display: 'flex', gap: 10, alignItems: 'baseline',
            }}>
              <span style={{ color:'rgba(100,210,200,0.45)', fontWeight:700, fontSize:12, letterSpacing:'0.05em' }}>{sec.num}</span>
              {sec.title}
            </h2>
            {sec.body.split('\n\n').map((para, i) => (
              <p key={i} style={{
                fontSize: 12, lineHeight: 1.85,
                color: 'rgba(180,200,200,0.4)',
                marginBottom: 12,
                whiteSpace: 'pre-line',
              }}>
                {para}
              </p>
            ))}
          </div>
        ))}

        {/* Acknowledgment box */}
        <div style={{
          padding:'24px 28px', borderRadius:10,
          background:'rgba(100,210,200,0.04)',
          border:'1px solid rgba(100,210,200,0.15)',
          marginTop:16,
        }}>
          <p style={{ fontSize:12, lineHeight:1.8, color:'rgba(180,200,200,0.5)', fontStyle:'italic' }}>
            By creating an account or using the HomeCalc Platform, you represent that you are at least 18 years of age,
            have the legal capacity to enter into a binding agreement, have read and understood these Terms of Service,
            and agree to be bound by all terms and conditions set forth herein.
          </p>
        </div>

        <div style={{ marginTop:36, display:'flex', gap:16, flexWrap:'wrap' }}>
          <Link href="/" style={{
            padding:'10px 22px', borderRadius:7,
            background:'rgba(255,255,255,0.05)', color:'rgba(208,216,216,0.6)',
            fontSize:12, fontWeight:600, textDecoration:'none',
            border:'1px solid rgba(255,255,255,0.1)',
          }}>
            ← Back to Home
          </Link>
          <Link href="/signup" style={{
            padding:'10px 22px', borderRadius:7,
            background:'#d8f0ec', color:'#0a0f1e',
            fontSize:12, fontWeight:800, textDecoration:'none',
          }}>
            Create Free Account →
          </Link>
        </div>
      </main>

      {/* Footer */}
      <footer style={{
        borderTop:'1px dashed rgba(255,255,255,0.07)',
        padding:'18px 40px',
        display:'flex', justifyContent:'space-between', alignItems:'center', flexWrap:'wrap', gap:8,
      }}>
        <span style={{ fontSize:12, fontWeight:900, color:'rgba(208,216,216,0.2)', letterSpacing:'-0.02em' }}>🏠 HomeCalc</span>
        <span style={{ fontSize:10, color:'rgba(208,216,216,0.15)' }}>© 2026 HomeCalc. All rights reserved.</span>
        <span style={{ fontSize:10, color:'rgba(208,216,216,0.15)' }}>For informational use only. Not financial advice.</span>
      </footer>
    </div>
  )
}
